message: Hello from Microservice Config Server
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9002/eureka/
  instance:
    hostname: localhost