message: Hello from Movie Service application
server:
  port: 9011
management:
  security:
    enabled: false
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9002/eureka/
  instance:
    hostname: localhost
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: movies