message: Hello from Movie Review Service application
server:
  port: 9012
management:
  security:
    enabled: false
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: movie-reviews