message: Hello from Movie Service application
server:
  port: 9011
management:
  security:
    enabled: false
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: movies